lista3.07:lista3.07.o util.o
	gcc $(path_obj)lista2.21.o $(path_obj)util.o -o $(path_bin)lista2.21

lista3.07.o: lista3/lista3.07/lista3.07.c
	gcc -o $(path_obj)lista2.21.o -c lista3/listalista3.07/llista3.07.c
