lista5.02: strparaint.o lista5.02.o
	gcc $(path_obj)lista5.02.o $(path_obj)strparaint.o -o $(path_bin)lista5.02

lista5.02.o: trabalho5/lista5/lista5.02/lista5.02.c
	gcc -o $(path_obj)lista5.02.o -c trabalho5/lista5/lista5.02/lista5.02.c

strparaint.o: trabalho5/lista5/lista5.02/strparaint.c
	gcc -o $(path_obj)strparaint.o -c trabalho5/lista5/lista5.02/strparaint.c

