int calc_pow(int x, int z);
int qtd_num(int num);
int is_perfect(int num);
float arctan(float x);
float power(float x,float y);
float alfa(float x, float y);
int serie_repetition(int n);
float s_sort(float *vetor1,float n);
int is_higher(int x, int y);
int mdc (int x, int y);
int is_pair(int x);
